#!/usr/bin/env bash

# Get brightness
get_backlight() {
	LIGHT=$(brightnessctl g)
	echo "${LIGHT}%"
}

# Increase brightness
inc_backlight() {
	brightnessctl set 5%+ # ends up being 10 for some reason idfk
}

# Decrease brightness
dec_backlight() {
	brightnessctl set 5%- # ends up being 10 for some reason idfk
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	brightnessctl g
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	get_backlight
fi
